// <auto-generated />
namespace AbstractQueueUnitTests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class dates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dates));
        
        string IMigrationMetadata.Id
        {
            get { return "201708071412420_date-s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
